# See https://pre-commit.com for more information
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      # - id: check-toml
      - id: check-json
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: poetry run pytest
        always_run: true
        pass_filenames: false
        language: system
        stages: ["push"]
