# List commands
default:
  @just --list

# Set up uv/python environment
init:
  pre-commit install
  pre-commit autoupdate
  uv sync --all-groups

# Run linters linters
lint:
  uv run ruff check .
  uv run mypy {{ cookiecutter.python_module_name }}
  uv run ruff format --diff | bat -l diff -p

# Run pytest with supplied options
@test *options:
  uv run pytest --cov={{ cookiecutter.python_module_name }} {% raw %}{{options}}{% endraw %}
  uv run coverage html

# Run linters in fix mode
fix:
  uv run ruff check . --fix
  uv run ruff format

# Build docs
docs *type:
  uv run {% raw %}{{ if type == "live" { "sphinx-autobuild" } else { "sphinx-build" } }}{% endraw %} -b html docs docs/_build/html

# Publish package to PyPI
publish:
  # Using PyPI token from UV_PUBLISH_TOKEN
  # Build package
  uv build
  # Publish package
  uv publish

docker_socket := `docker context inspect --format '{% raw %}{{.Endpoints.docker.Host}}{% endraw %}'`
docker_status := `limactl ls --json | jq -r 'select(.name == "docker") | .status'`

# act shortcut
act *options:
  [[ {% raw %}{{docker_status}}{% endraw %} == "Running" ]] || limactl start docker
  act --container-daemon-socket {% raw %}{{docker_socket}} {{options}}{% endraw %}
